### ISSUE TITLE
broken with latest sprockets 3.7.1

### ISSUE THREAD

**Issue by josh-m-sharpe** [AlexanderPavlenko/sprockets_uglifier_with_source_maps#4]
Looks like sprockets moved where @uglifier is set:

https://github.com/rails/sprockets/commit/10e6d81ae0fde4830c29a88b74432dbc7672911c

so now this gem is showing:

remote:        NoMethodError: undefined method `compile_with_map' for nil:NilClass
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/bundler/gems/sprockets_uglifier_with_source_maps-72235058aff3/lib/sprockets_uglifier_with_source_maps/compressor.rb:20:in `call'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:28:in `call'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:134:in `block in find'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `each'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `find'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
remote:        /tmp/build_e870f0c72abf6ad9a62d96ffb176160d/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'

**Comment by josh-m-sharpe** [comment]
Think this fixes it
https://github.com/AlexanderPavlenko/sprockets_uglifier_with_source_maps/pull/5
